gas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from main.views import *
from . import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^sjsadminpanel/', include(admin.site.urls)),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^product/([0-9]+)', product, name='product'),
    url(r'^catalog/([0-9]+)', product_list, name='product_list'),
    url(r'^catalog/', catalog, name='catalog'),
    url(r'^addspecification/([0-9]+)', addSpecification, name='add_specification'),
    url(r'^about/', about, name='about'),
	url(r'^$', index, name='index'),
]

#if settings.DEBUG:
#	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#	urlpatterns += staticfiles_urlpatterns()

main/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from redactor.fields import RedactorField



class Category(models.Model):
	title = models.CharField(max_length=300, unique=True)

	class Meta:
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'

	def __str__(self):
		return '{}'.format(self.title)

class Product(models.Model):
	title = models.CharField(max_length=300, verbose_name="Название")
	category = models.ForeignKey(Category)
	desctiption = RedactorField(max_length=3000, verbose_name="Описание")
	text = RedactorField(max_length=3000, verbose_name="Особенности", blank=True)
	image = models.ImageField(upload_to='images/')
	specification_image = models.ImageField(upload_to='images/specifications')
	promoted = models.BooleanField(default=False)
	promoted_name = models.CharField(max_length=300)	

	class Meta:
		verbose_name = 'Продукт'
		verbose_name_plural = 'Продукты'

	def __str__(self):
		return '{}'.format(self.title)

	def admin_thumbnail(self):
		return u'<img src="{0}" height="300px"/>'.format(self.image.url)

	admin_thumbnail.short_description = 'Thumbnail'
	admin_thumbnail.allow_tags = True

#type of column in specification table
class SpecificationField(models.Model):
	product = models.ForeignKey(Product)
	title = models.CharField(max_length=400)
	measure = models.CharField(max_length=50, blank=True)

	class Meta:
		verbose_name = 'Поле спецификации'
		verbose_name_plural = 'Поля спецификации'

	def __str__(self):
		return '{}'.format(self.title)

#specification row
class SpecificationInstance(models.Model):
	product = models.ForeignKey(Product)
	index = models.CharField(max_length=100)
	number= models.IntegerField()

	class Meta:
		verbose_name = 'Экземпляр спецификации'
		verbose_name_plural = 'Экземпляры спецификации'
		ordering = ['number']

	def __str__(self):
		return '{}'.format(self.index)

	def selflink(self):
		if self.id:
			return "<a href='/admin/main/specificationinstance/{}' target='_blank'>Edit</a>".format(self.id)
		else:
			return "Not present"

	selflink.allow_tags = True

#value that write in cell
class SpecificationInstanceValue(models.Model):
	specification_instance = models.ForeignKey(SpecificationInstance)
	specification_field = models.ForeignKey(SpecificationField)
	value = models.CharField(max_length=1500)


	class Meta:
		verbose_name = 'Значение поля спецификации'
		verbose_name_plural = 'Значения полей спецификации'
#Table of texts
class Texts(models.Model):
	title = models.CharField(max_length=200, verbose_name='Название')
	text = RedactorField(max_length=3000, verbose_name='Текст')

class News(models.Model):
	date_created = models.DateTimeField(auto_now_add=True)
	title = models.CharField(max_length=500, verbose_name='Название новости')
	text = RedactorField(max_length=3000, verbose_name='Текст новости')

main/views.py
from django.shortcuts import render, render_to_response
from main.models import *
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
import random
import json



def index(request):
	cs = Category.objects.all()
	news = News.objects.all()
	promoted_products = Product.objects.filter(promoted=True)
	index = True
	return render_to_response('index.html', context={'categories' : cs, 'news':news[0:3],'promoted_products':promoted_products, 'index':True})

def catalog(request):
	cs = Category.objects.all()
	return render_to_response('category.html', context={'categories' : cs})

def product_list(request, category_id):
	cs = Category.objects.all()
	category = Category.objects.get(id=category_id)
	ps = Product.objects.filter(category__id=category_id)
	return render_to_response('product_list.html', context={'products' : ps,  'category_id':category_id, 'category':category, 'categories':cs})

def product(request, product_id):
	cs = Category.objects.all()
	prod = Product.objects.get(id=product_id)
	user = request.user; 
	return render_to_response('product.html', context={'product':prod,'user':user, 'categories':cs})

@login_required
def addSpecification(request, id):
	cs = Category.objects.all()
	if request.POST:
		product = Product.objects.get(id=id)
		data = json.loads(request.body.decode('utf-8'))
		specs = data['specs']
		fields = data['fields']
		print(fields)
		#parsing json'а сначала все спецификации потом все значения
		for i in range(0, len(specs)):
			new_spec = SpecificationInstance(product=product, index=specs[i], number=i+1)
			new_spec.save()
		for i in range(0, len(fields)):
			new_field = SpecificationField(product=product, title=fields[i]['field'], measure=fields[i]['measure'])
			new_field.save()

			for j in range(0, len(fields[i]['values'])):
				
				print(SpecificationInstance.objects.filter(index=fields[i]['values'][j]['specification'])[0].id)
				new_specification_value = SpecificationInstanceValue(specification_field=new_field, specification_instance=SpecificationInstance.objects.filter(index=fields[i]['values'][j]['specification'])[0], value=fields[i]['values'][j]['value'])
				new_specification_value.save()
		return HttpResponse('Added')
	return render_to_response('specification_add.html', context={'product_id':id, 'categories':cs})

def about(request):
	cs = Category.objects.all()
	return render_to_response('about.html', context={'categories':cs})

# Custom filters

templates/about.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Главная</title>
	<link rel="shortcut icon" type="image/x-ico" href="{% static 'img/favicon.ico' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/pure-min.css" %}">
	<link rel="stylesheet" href="{% static "css/remodal.css" %}">
	<link rel="stylesheet" href="{% static "css/remodal-default-theme.css" %}">
	<script type="text/javascript" src="{% static "js/jquery-3.0.0.min.js" %}"></script>
	<script type="text/javascript" src="{% static "js/script.js" %}"></script>
	<script type="text/javascript" src="{% static "js/remodal.js" %}"></script>
	<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter37983560 = new Ya.Metrika({ id:37983560, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, ut:"noindex" }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/37983560?ut=noindex" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
</head>
<body>

	<header>
		<div class="header-logo">
			<img class="header__img-logo" src="{% static "img/logo.png"%}">
			<img class="header__img-title" src="{% static "img/title.png"%}">
		</div>
		<div class="header-menu pure-menu pure-menu-horizontal">
		    <ul class="pure-menu-list">
		        <li class="pure-menu-item"><a href="/" class="pure-menu-link">Главная</a></li>
		        <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
		            <a id="menuLink1" class="pure-menu-link">Каталог</a>
		            <ul class="pure-menu-children">

		            	{% for c in categories %}
		            		<li class="pure-menu-item"><a href="/catalog/{{c.id}}" class="pure-menu-link">{{c.title}}</a></li>
		            	{% endfor %}
		                <!--<li class="pure-menu-item"><a href="#" class="pure-menu-link">1</a></li>
		                <li class="pure-menu-item"><a href="#" class="pure-menu-link">2</a></li>
		                <li class="pure-menu-item"><a href="#" class="pure-menu-link">3</a></li> -->
		            </ul>
		        </li>
		        <li class="pure-menu-item"><a href="{% url 'about' %}" class="pure-menu-link">Контакты</a></li>
		        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Новости</a></li>
		    </ul>
		</div>

	</header>

	<main>
			<br/>

		<div class="about-text">
			<p>Компания "Advanced Cmpletion Equipment" OOO "ACE" основана в 2014 году. Располагается в Санкт-Петербурге.
			Одним из направлений работы является оказание консультаций при выборе, дальнейшая организация продаж и сервис внутрискважинного оборудования. Предлагаемое нами внутрискважинное оборудование производится на совместном американо-китайском предприятии SERVA SJS, расположенном в провинции Хубей на берегу реки Янцзы в центральной части Китая.</p>
			<p>Производственная компания SERVA SJS сертифицирована по программам качества ISO 9001 и DNV с 1999 года. Внутрискважинное оборудование сертифицировано по API 11D1 с 2005 года.</p>
			<p>Уникальная, современная и мощная производственная база, использование новейших технологий и материалов, позволяет реализовать самые смелые замыслы в интересах заказчиков, решать сложнейший задачи.</p>
			<p class="about-text__important">Главными целями компании являются надёжность в партнерстве, качество в работе, уверенность в будущем!</p>

			<div class="about-text__contacts">

				<div id="map" style="width:100%;height:300px;margin: 35px auto 50px auto;">
			</div>

				<div class="about-text__images">
					<img width="300px" src="{% static 'img/about-pics.png'%}">
				</div>
				<div class="about-text__text-contacts">
					<div class="about-text__contacts-title">
						<p>Advanced Completion Equipment</p>
					</div>
					<p>Адрес: Санкт-Петербург</p>
					<p>В.О., 13 линия, 78 оф. 455</p>
					<p>тел./факс: +7 (812) 336 82 41</p>
					<p>www.ace-spb.ru</p>
				</div>

			</div>
		</div>
		
		
		<script>
			function initMap() {
				var myLatLng = {lat: 59.946826, lng: 30.263755};
			    var mapDiv = document.getElementById('map');
			    var map = new google.maps.Map(mapDiv, {
		          center: myLatLng,
		          zoom: 16
		        });
		        var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';
		        var marker = new google.maps.Marker({
				  position: myLatLng,
				  map: map,
				});
			};
		</script>
		<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
        async defer></script>
	
	</main>

	<footer>
		<div class="footer-text">
			<p>
				Advanced Completion Equipment. 
				<br> 
				2016 СПб, В.О.  13 линия 78, оф. 455 
				<br>
				 email: info@ace-spb.ru <br> +7 (812) 336 82 41
			 </p>
		</div>
	</footer>

</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Главная</title>
	<link rel="shortcut icon" type="image/x-ico" href="{% static 'img/favicon.ico' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/pure-min.css" %}">
	<link rel="stylesheet" href="{% static "css/remodal.css" %}">
	<link rel="stylesheet" href="{% static "css/remodal-default-theme.css" %}">
	<script type="text/javascript" src="{% static "js/jquery-3.0.0.min.js" %}"></script>
	<script type="text/javascript" src="{% static "js/script.js" %}"></script>
	<script type="text/javascript" src="{% static "js/remodal.js" %}"></script>
	<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter37983560 = new Ya.Metrika({ id:37983560, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, ut:"noindex" }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/37983560?ut=noindex" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
</head>
<body>

	<header>
		<div class="header-logo">
			<img class="header__img-logo" src="{% static "img/logo.png"%}">
			<img class="header__img-title" src="{% static "img/title.png"%}">
		</div>
		<div class="header-menu pure-menu pure-menu-horizontal">
		    <ul class="pure-menu-list">
		        <li class="pure-menu-item"><a href="/" class="pure-menu-link">Главная</a></li>
		        <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
		            <a id="menuLink1" class="pure-menu-link">Каталог</a>
		            <ul class="pure-menu-children">

		            	{% for c in categories %}
		            		<li class="pure-menu-item"><a href="/catalog/{{c.id}}" class="pure-menu-link">{{c.title}}</a></li>
		            	{% endfor %}
		                <!--<li class="pure-menu-item"><a href="#" class="pure-menu-link">1</a></li>
		                <li class="pure-menu-item"><a href="#" class="pure-menu-link">2</a></li>
		                <li class="pure-menu-item"><a href="#" class="pure-menu-link">3</a></li> -->
		            </ul>
		        </li>
		         <li class="pure-menu-item"><a href="{% url 'about' %}" class="pure-menu-link">Контакты</a></li>
		        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Новости</a></li>
		    </ul>
		</div>

	</header>

	<main>

		<div class="banner-wrapper">
			<section class="banner">
				<div class="banner-info">
					<p>Advanced Completion Equipment. <br> 2016 СПб, В.О.  13 линия 78, оф. 455 <br> email: info@ace-spb.ru <br> +7 (812) 336 82 41</p>
				</div>
			</section>
		</div>
	
		<div class="index-info-wrapper">

			<section class="index-toggled-menu">
	
				<div class="index-menu-toggler">

					<div class="header-menu pure-menu pure-menu-horizontal">
					    <ul class="pure-menu-list">
					        <li onclick="show_promoted();" class="pure-menu-item"><a class="pure-menu-link">Предложения</a></li>
					        <li onclick="show_categories();" class="pure-menu-item"><a class="pure-menu-link">Разделы</a></li>
					    </ul>
					</div>
				</div>

				<div class="index-promoted-products">
				{% for pp in promoted_products %}
					<div class="promoted-product">
						<div class="promoted-product__category">
							<a href="/catalog/{{pp.category.id}}" >{{pp.category.title}}
						</div>
						<div class="promoted-product__main">
							<div class="promoted-product__title">
								{% if pp.promoted_name != '0' %}
									<a href="/product/{{pp.id}}" >{{pp.promoted_name}}</a>
								{% else %}
									<a href="/product/{{pp.id}}" >{{pp.title}}</a>
								{% endif %}
							</div>
							<div class="promoted-product__buttons">
								<img data-title="{{pp.title}}" data-image-url="{{pp.image.url}}" onclick="show_modal(this)" src="{% static "img/picture-icon.png" %}">
								<a href="/product/{{pp.id}}" >Подробнее...</a>
								
							</div>
						</div>
					</div>
				{% endfor %}

				</div>

				<div class="index-categories" style="display:none">
					{% for c in categories %}
						
						<div class="index-category">
							<a href="/catalog/{{c.id}}">
								<h1 class="index-category__title">{{c.title}}</h1>
							</a>
						</div>
						
					{% endfor %}
					
				</div>

			</section>

			<section class="index-text">
			</section>

		</div>
	

		<div class="remodal-bg">
			<div data-remodal-id="modal">
				<button data-remodal-action="close" class="remodal-close"></button>
				<h1 class="modal-title">Remodal</h1>
				<img style="max-width:200px;max-height:400px;" class="modal-image" src="" alt="">
			</div>
		</div>
	</main>

	<footer>
		<div class="footer-text">
			<p>
				Advanced Completion Equipment. 
				<br> 
				2016 СПб, В.О.  13 линия 78, оф. 455 
				<br>
				 email: info@ace-spb.ru <br> +7 (812) 336 82 41
			 </p>
		</div>
	</footer>

	<script type="text/javascript">
		var options = {};
   		var remod = $('[data-remodal-id=modal]').remodal(options);
	</script>

</body>
</html>

templates/product.html
{% load static %}
{% load next %}
{% load specification_cell_filter %}
<!DOCTYPE html>
<html>
<head>
	<title>{{product.title}}</title>
	<link rel="shortcut icon" type="image/x-ico" href="{% static 'img/favicon.ico' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/pure-min.css" %}">
	<script type="text/javascript" src="{% static "js/script.js" %}"></script>
	<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter37983560 = new Ya.Metrika({ id:37983560, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, ut:"noindex" }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/37983560?ut=noindex" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->
</head>

<body>

	<header>
		<div class="header-logo">
			<img class="header__img-logo" src="{% static "img/logo.png"%}">
			<img class="header__img-title" src="{% static "img/title.png"%}">
		</div>
		<div class="header-menu pure-menu pure-menu-horizontal">
		    <ul class="pure-menu-list">
		        <li class="pure-menu-item"><a href="/" class="pure-menu-link">Главная</a></li>
		        <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
		            <a  id="menuLink1" class="pure-menu-link">Каталог</a>
		            <ul class="pure-menu-children">

		            	{% for c in categories %}
		            		<li class="pure-menu-item">
		            			<a href="/catalog/{{c.id}}" class="pure-menu-link">{{c.title}}</a>
		            		</li>
		            	{% endfor %}
		                <!--<li class="pure-menu-item"><a href="#" class="pure-menu-link">1</a></li>
		                <li class="pure-menu-item"><a href="#" class="pure-menu-link">2</a></li>
		                <li class="pure-menu-item"><a href="#" class="pure-menu-link">3</a></li> -->
		            </ul>
		        </li>
		         <li class="pure-menu-item"><a href="{% url 'about' %}" class="pure-menu-link">Контакты</a></li>
		        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Новости</a></li>
		    </ul>
		</div>

	</header>

	<main class="product-main">

		<div class="product-wrapper">
			<div class="product-text">
				<div class="product-text-title">
					<h3><a href="{% url 'product_list' product.category.id %}">{{product.category}}</a>/{{product.title}}</h3>
				</div>
				<hr>
				<div class="product-text-description">
					<h2>Описание</h2>
					{{product.desctiption | safe }}	
				</div>
				<hr>
				<div class="product-text-text">
					<h2>Особенности</h2>
					{{product.text | safe }}
				</div>
			</div>
			<div class="product-options">
				<div class="index-menu-toggler">
					<div class="header-menu pure-menu pure-menu-horizontal">
					    <ul class="pure-menu-list">
					        <li onclick="show_specification();" class="pure-menu-item"><a class="pure-menu-link">Спецификация</a></li>
					        <li onclick="show_product_image();" class="pure-menu-item"><a class="pure-menu-link">Изображение</a></li>
					    </ul>
					</div>
				</div>
				<div class="product-options-specification">
					{% if product.specificationinstance_set.all %}
						
						<div class="product-options-table-style-title">
							Спецификации
						</div>
		
							<table width="100%" class="pure-table pure-table-bordered">
								<thead>
									<th rowspan="2" class="table-index-row">
										Номер по каталогу
									</th>
									{% for field in product.specificationfield_set.all %}
										{% if field.measure %}
											<th>
												{{ field.title }}
											</th>
										{% else %}
											<th rowspan="2">
												{{ field.title }}
											</th>
										{% endif %}
									{% endfor %}
									
								
								
								<tr>
										
										{% for field in product.specificationfield_set.all %}
											
												{% if field.measure %}<th>{{ field.measure }}</th>{% endif %}
											
										{% endfor %}
								</tr>
								</thead>
								<tbody>
									{% for row in product.specificationinstance_set.all %}

											
											<tr>
												
												<td class="table-index-row">
													{{row.index|safe}}
												</td>

												{% for field in product.specificationfield_set.all %}

													{% if field|specification_cell_filter:row %}
														{{field|specification_cell_filter:row|safe}}
													{% endif %}

												{% endfor %}

											</tr>

									{% endfor %}

							</tbody>
							</table>
					{% else %}
						{% if product.specification_image %}
							<img class="specification-image" src="{{product.specification_image.url}}">
						{% else %}
							{% if user.is_authenticated %}
								<a href="{% url 'add_specification' product.id %}">Добавить спецификацию</a>
							{% endif %}
						{% endif %}

					{% endif %}
				</div>
				<div class="product-options-image" style="display:none">
					<button class="pure-button" onclick="resize_image('minus');">Уменьшить</button>
					<button class="pure-button" onclick="resize_image('plus');">Увеличить</button>
					<br>
					<br>
					<img class="product-image" style="width:200px"; src="{{product.image.url}}" >
				</div>
			</div>
		</div>



	</main>

	<footer>
		<div class="footer-text">
			<p>
				Advanced Completion Equipment. 
				<br> 
				2016 СПб, В.О.  13 линия 78, оф. 455 
				<br>
				 email: info@ace-spb.ru <br> +7 (812) 336 82 41
			 </p>
		</div>
	</footer>

	<script>

		var image;
		var image_width_init = -1;

		window.onload = function(){
			image = document.getElementsByClassName('product-image')[0];
			image_width_init = image.offsetWidth;
			console.log(image_width_init);
		};
		

		function resize_image(resize_type){

			if (resize_type=="minus"){
				if (image.offsetWidth - 50 > 0){
					image.style.width = (image.offsetWidth - 50) + "px";
				}
			} else if (resize_type=="plus") {
				if (image.offsetWidth + 50 < 400 ){
					image.style.width = (image.offsetWidth + 50) + "px";
				}
			}
		}

	</script>
</body>
</html>